AWSTemplateFormatVersion: '2010-09-09'
Description: 'ReviewMaster API Revision Upload Module - /revision-upload endpoint resources and methods'

# =====================================================================================================================
# PARAMETERS SECTION
# =====================================================================================================================

Parameters:
  # API Gateway References
  RestApiId:
    Type: String
    Description: "REST API ID from API Gateway module"
    
  RestApiRootResourceId:
    Type: String
    Description: "REST API Root Resource ID from API Gateway module"
    
  # Lambda Function Reference
  RevisionCheckerLambdaArn:
    Type: String
    Description: "Revision Checker Lambda Function ARN from Compute module"

# =====================================================================================================================
# RESOURCES SECTION
# =====================================================================================================================

Resources:

  # === RESOURCES ===

  # /revision-upload リソース
  RevisionUploadResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      ParentId: !Ref RestApiRootResourceId
      PathPart: "revision-upload"

  # /revision-upload/{reviewId} リソース
  RevisionUploadReviewIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      ParentId: !Ref RevisionUploadResource
      PathPart: "{reviewId}"

  # === METHODS ===

  # /revision-upload OPTIONS Method (CORS)
  RevisionUploadOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref RevisionUploadResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # /revision-upload/{reviewId} OPTIONS Method (CORS)
  RevisionUploadReviewIdOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref RevisionUploadReviewIdResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # /revision-upload/{reviewId} POST Method
  RevisionUploadPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref RevisionUploadReviewIdResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations"
          - LambdaArn: !Ref RevisionCheckerLambdaArn
      MethodResponses:
        - StatusCode: "200"
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # === LAMBDA PERMISSIONS ===

  RevisionCheckerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RevisionCheckerLambdaArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*/*"

# =====================================================================================================================
# OUTPUTS SECTION
# =====================================================================================================================

Outputs:
  RevisionUploadResourceId:
    Description: "Revision Upload Resource ID"
    Value: !Ref RevisionUploadResource
    Export:
      Name: !Sub "${AWS::StackName}-RevisionUploadResourceId"
      
  RevisionUploadReviewIdResourceId:
    Description: "Revision Upload ReviewId Resource ID"
    Value: !Ref RevisionUploadReviewIdResource
    Export:
      Name: !Sub "${AWS::StackName}-RevisionUploadReviewIdResourceId"
      
  MethodsCount:
    Description: "Number of methods implemented in this module"
    Value: "3" 