AWSTemplateFormatVersion: '2010-09-09'
Description: 'ReviewMaster API Revision Status Module - /revision-status endpoint resources and methods'

# =====================================================================================================================
# PARAMETERS SECTION
# =====================================================================================================================

Parameters:
  # API Gateway References
  RestApiId:
    Type: String
    Description: "REST API ID from API Gateway module"
    
  RestApiRootResourceId:
    Type: String
    Description: "REST API Root Resource ID from API Gateway module"
    
  # Lambda Function Reference
  RevisionCheckerLambdaArn:
    Type: String
    Description: "Revision Checker Lambda Function ARN from Compute module"

# =====================================================================================================================
# RESOURCES SECTION
# =====================================================================================================================

Resources:

  # === RESOURCES ===

  # /revision-status リソース
  RevisionStatusResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      ParentId: !Ref RestApiRootResourceId
      PathPart: "revision-status"

  # /revision-status/{reviewId} リソース
  RevisionStatusReviewIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      ParentId: !Ref RevisionStatusResource
      PathPart: "{reviewId}"

  # /revision-status/{reviewId}/{revisionNumber} リソース
  RevisionStatusRevisionNumberResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      ParentId: !Ref RevisionStatusReviewIdResource
      PathPart: "{revisionNumber}"

  # === METHODS ===

  # /revision-status OPTIONS Method (CORS)
  RevisionStatusOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref RevisionStatusResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # /revision-status/{reviewId} OPTIONS Method (CORS)
  RevisionStatusReviewIdOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref RevisionStatusReviewIdResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # /revision-status/{reviewId}/{revisionNumber} OPTIONS Method (CORS)
  RevisionStatusRevisionNumberOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref RevisionStatusRevisionNumberResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # /revision-status/{reviewId}/{revisionNumber} GET Method
  RevisionStatusGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref RevisionStatusRevisionNumberResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations"
          - LambdaArn: !Ref RevisionCheckerLambdaArn
      MethodResponses:
        - StatusCode: "200"
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # === LAMBDA PERMISSIONS ===

  RevisionCheckerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RevisionCheckerLambdaArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*/*"

# =====================================================================================================================
# OUTPUTS SECTION
# =====================================================================================================================

Outputs:
  RevisionStatusResourceId:
    Description: "Revision Status Resource ID"
    Value: !Ref RevisionStatusResource
    Export:
      Name: !Sub "${AWS::StackName}-RevisionStatusResourceId"
      
  RevisionStatusRevisionNumberResourceId:
    Description: "Revision Status Revision Number Resource ID"
    Value: !Ref RevisionStatusRevisionNumberResource
    Export:
      Name: !Sub "${AWS::StackName}-RevisionStatusRevisionNumberResourceId"
      
  MethodsCount:
    Description: "Number of methods implemented in this module"
    Value: "4" 